name: posts_clean_architecture
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1 #functional programing
  equatable: ^2.0.5
  get_it: ^7.2.0 
  internet_connection_checker: ^0.0.1+1
  http: ^0.13.5
  shared_preferences: ^2.0.15


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

